### ISSUE TITLE
catkinization

### ISSUE THREAD

**Issue by fevb** [gborghesan/camera_robot_calibration#1]
Hi,

I have a catkinized version of this package available at https://github.com/fevb/camera_robot_calibration

Would you consider opening a new 'hydro' branch so that I can merge my repo?

**Comment by gborghesan** [comment]
I will do next week... Holiday still...
Did you try? 
Worked?

**Comment by fevb** [comment]
Works fine in hydro for me

**Comment by gborghesan** [comment]
if you have a github account i can add as a collaborator?

2014-08-21 18:29 GMT+02:00 Francisco Vina notifications@github.com:

**Comment by fevb** [comment]
Yes, my account is  @fevb

**Comment by fevb** [comment]
Ok I've pushed the catkinized version into a new 'hydro' branch.
